#!/usr/bin/env python3
"""
Scans toml-pretty-deser/examples/ for e*.rs example files.

Outputs:
  - toml-pretty-deser/examples/manifest.txt  (sorted list of example filenames)
  - toml-pretty-deser/examples/EXAMPLES.md   (combined markdown with descriptions and source)
"""

import os
import re
import sys

EXAMPLES_DIR = os.path.join(
    os.path.dirname(__file__), "..", "toml-pretty-deser", "examples"
)


def find_examples():
    """Find all e*.rs files in the examples directory, sorted."""
    files = sorted(f for f in os.listdir(EXAMPLES_DIR) if re.match(r"e\d+.*\.rs$", f))
    return files


def extract_doc_comment(filepath):
    """Extract //! doc comments from the top of a file."""
    lines = []
    with open(filepath, "r") as f:
        for line in f:
            if line.startswith("//!"):
                # Strip the //! prefix and at most one leading space
                content = line[3:]
                if content.startswith(" "):
                    content = content[1:]
                lines.append(content.rstrip())
            elif line.strip() == "":
                continue  # skip blank lines between doc comments
            else:
                break
    return "\n".join(lines)


def write_manifest(examples):
    """Write manifest.txt with sorted example filenames."""
    manifest_path = os.path.join(EXAMPLES_DIR, "manifest.txt")
    with open(manifest_path, "w") as f:
        for name in examples:
            f.write(name + "\n")
    print(f"Wrote {manifest_path} ({len(examples)} examples)")


def write_examples_md(examples):
    """Write examples/README.md combining all examples with descriptions and source."""
    md_path = os.path.join(EXAMPLES_DIR, "README.md")
    with open(md_path, "w") as f:
        f.write("# toml-pretty-deser Examples\n\n")
        f.write(
            "Auto-generated by `dev/collect_examples.py`. "
            "Do not edit manually.\n\n"
            "To run any example, clone the repo and e.g. `cargo run -p toml-pretty-deser --example e14_improve_errors`\n\n"
        )
        f.write("---\n\n")

        for name in examples:
            filepath = os.path.join(EXAMPLES_DIR, name)
            example_name = name.replace(".rs", "")
            description = extract_doc_comment(filepath)

            f.write(f"## `{example_name}`\n\n")
            if description:
                f.write(description + "\n\n")

            f.write(
                f"**Run:** `cargo run -p toml-pretty-deser --example {example_name}`\n\n"
            )

            with open(filepath, "r") as src:
                source = src.read()
            f.write("<details>\n<summary>Source code</summary>\n\n")
            f.write(f"```rust\n{source}```\n\n")
            f.write("</details>\n\n---\n\n")

    print(f"Wrote {md_path}")


def main():
    examples = find_examples()
    if not examples:
        print("No examples found!", file=sys.stderr)
        sys.exit(1)

    print(f"Found {len(examples)} examples:")
    for name in examples:
        print(f"  {name}")

    write_manifest(examples)
    write_examples_md(examples)
    print("Done.")


if __name__ == "__main__":
    main()
