/// Verifies that the examples manifest (generated by `dev/collect_examples.py`)
/// matches the actual example files on disk.
///
/// If this test fails, run: `python dev/collect_examples.py`
#[test]
fn manifest_matches_actual_examples() {
    let examples_dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("examples");
    let manifest_path = examples_dir.join("manifest.txt");

    // Read manifest
    let manifest_content = std::fs::read_to_string(&manifest_path).unwrap_or_else(|e| {
        panic!(
            "Could not read {}: {e}\nRun `python dev/collect_examples.py` to generate it.",
            manifest_path.display()
        )
    });
    let mut manifest_entries: Vec<&str> =
        manifest_content.lines().filter(|l| !l.is_empty()).collect();
    manifest_entries.sort();

    // Read actual files
    let mut actual_files: Vec<String> = std::fs::read_dir(&examples_dir)
        .expect("Could not read examples directory")
        .filter_map(|entry| {
            let entry = entry.ok()?;
            let name = entry.file_name().to_string_lossy().to_string();
            if name.starts_with('e')
                && name.ends_with(".rs")
                && name.chars().nth(1).is_some_and(|c| c.is_ascii_digit())
            {
                Some(name)
            } else {
                None
            }
        })
        .collect();
    actual_files.sort();

    assert_eq!(
        manifest_entries,
        actual_files.iter().map(String::as_str).collect::<Vec<_>>(),
        "Manifest does not match actual examples. Run `python dev/collect_examples.py` to update."
    );
}
